DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS CATALOG_DETAIL;
DROP TABLE IF EXISTS CATALOG;

CREATE TABLE BRAND(
    BRAND_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BRAND_NAME VARCHAR(15)
);

CREATE TABLE CATALOG(
    CATALOG_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATALOG_NAME VARCHAR(15)
);

CREATE TABLE CATALOG_DETAIL(
    CATALOG_DETAIL_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATALOG_ID INT(11) NOT NULL,
    CATALOG_DETAIL_NAME VARCHAR(15),
    FOREIGN KEY (CATALOG_ID) REFERENCES CATALOG(CATALOG_ID)
);

CREATE TABLE PRICES(
    PRICE_ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT(11) NOT NULL,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT(11) NOT NULL,
    PRODUCT_ID INT(11) NOT NULL,
    PRIORITY INT(11) NOT NULL,
    PRICE DECIMAL(10,2),
    CURR VARCHAR(3),
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID)
);

